# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnicornVR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'PusherSwift', '~> 5.0.1'
 pod 'Alamofire'
  # Pods for UnicornVR

end
